### ISSUE TITLE
Migration between Volto sites

### ISSUE THREAD

**Issue by cekk** [collective/collective.exportimport#226]
I need to migrate some data between two Volto sites.
When i export the contents, there are some blocks serializers (adapters in plone.restapi) that converts internal links with resolveuid into a proper url.

This generates wrong/broken exports.

There should be a way to temporary disable these adapters and don't change blocks data.

Any idea about how to do it in a nice way?

**Comment by pbauer** [comment]
Good point, I think we will encounter the same issue in `plone.distribution`. 
The right way is probably to override the serializers.

**Comment by cekk** [comment]
Yes i thinked about that, but maybe there are some products that overrided them too (in both source and destination)

**Comment by fredvd** [comment]
The challenge is that the serializers are in multiple modules and were written for sometimes different purposes.

Maybe this issue is better solved in plone.exportimport, which is a rewritten version of collective.exportimport  with less dependencies and support for edge cases and older Plone versions.  It is meant to export/import content only on recent Plone 6 (Volto and ClassicUI) sites. plone.exportimport will likely be included in Plone 6.1 'core' because it will be a dependency of plone.distribution.

**Comment by davisagli** [comment]
By now, both collective.exportimport and plone.exportimport have adapters which disable the block transforms. We can close this.
